### ISSUE TITLE
Gulp tasks failing

### ISSUE THREAD

**Issue by niranjan-reddy** [website-templates/personal-portfolio_one-page-template#7]
Following your instructions when I execute any of the Gulp tasks it always give me the following error message on the console. Please help.

C:\someplace\CodeBases\project\>gulp dev
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\someplace\CodeBases\project\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\someplace\CodeBases\project\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\someplace\CodeBases\project\gulp_tasks\config\aliases.js:63:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by orlovmax** [comment]
Seems like you're using Gulp v4, and this template was configured for Gulp v3

A few months ago I tried to migrate to v4, but there were a few tricky issues in some of the tasks. So for now I left it as-is.

So the easiest way to make it work is to use gulp v3

**Comment by niranjan-reddy** [comment]
Thanks Maxim Orlov for the clarification. After downgrading the gulp version to 3.9.1 the tasks worked perfectly.

**Comment by niranjan-reddy** [comment]
Please update your package.json file and update the gulp version appropriately.
